spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mitinikitos/VkrProject/tree/master/config/src/main/resources/shared
          skipSslValidation: true
#        native.search-locations: classpath:/shared
#  profiles:
#    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
  main:
    banner-mode: OFF

server.port: 8888