spring:
  cloud:
    config:
      server:
        native.search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
  main:
    banner-mode: OFF

server.port: 8888
logging:
  pattern:
    console: